'use strict';
const { chooseRoomScene } = require('./ui-fixture.cjs');
const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict'), fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'album-client-ui-'));
const output = path.join(__dirname, '../test-results/client'); fs.mkdirSync(output, { recursive: true });
const report = { checks: [], pageErrors: [] }; let application, site;
async function launch() {
  const env = { ...process.env, ALBUM_DESKTOP_TEST_PROFILE: profile }; delete env.ELECTRON_RUN_AS_NODE;
  application = await electron.launch({ ...(process.env.ALBUM_QA_EXE ? { executablePath: path.resolve(process.env.ALBUM_QA_EXE), args: [] } : { args: [path.join(__dirname, '..')] }), env });
  await application.firstWindow();
  await application.evaluate(async ({ webContents }) => { const started = Date.now(); while (!webContents.getAllWebContents().some((contents) => contents.getURL().startsWith('https://album-circle.vercel.app'))) { if (Date.now() - started > 30000) throw new Error('Site view did not open'); await new Promise((resolve) => setTimeout(resolve, 100)); } });
  site = await application.waitForEvent('window', { predicate: (page) => page.url().startsWith('https://album-circle.vercel.app'), timeout: 5000 }).catch(() => application.windows().find((page) => page.url().startsWith('https://album-circle.vercel.app')));
  assert.ok(site); site.on('pageerror', (error) => report.pageErrors.push(error.message));
  await site.locator('.app-titlebar').waitFor({ timeout: 30000 });
  const welcome = site.getByRole('dialog', { name: '欢迎来到心流小屋', exact: true });
  if (await welcome.isVisible()) await welcome.getByRole('button', { name: '先逛逛小屋', exact: true }).click();
  await application.evaluate(({ BrowserWindow }) => { const window = BrowserWindow.getAllWindows()[0]; window.unmaximize(); window.setSize(1024, 768); });
  await site.waitForFunction(() => innerWidth <= 1100);
}
const check = (value) => report.checks.push(value);
(async () => {
  await launch();
  await site.locator('.cabin-pixel').waitFor(); assert.match(await site.locator('.app-brand small').innerText(), /0 张唱片/);
  await site.locator('.room-empty', { hasText: '等你放上第一张' }).waitFor(); check('fresh-start-opens-the-pixel-cabin-without-an-account');
  await site.getByRole('button', { name: '添加专辑', exact: true }).click();
  const add = site.getByRole('dialog', { name: '添加专辑' }); await add.getByRole('tab', { name: '手动填写' }).click();
  await add.getByLabel('专辑名').fill('本地验证专辑'); await add.getByLabel('歌手').fill('离线歌手'); await add.getByLabel('曲目').fill('第一首\n第二首');
  await add.getByRole('button', { name: /放上唱片架/ }).click(); await add.locator('.add-notice', { hasText: '本地验证专辑' }).waitFor();
  await add.getByRole('button', { name: '关闭添加专辑' }).click();
  await site.locator('.room-record').first().waitFor(); check('manual-album-persists-locally');
  await site.getByRole('button', { name: '自定义唱片', exact: true }).first().click();
  await site.getByLabel('黑胶底色', { exact: true }).fill('#aabbcc');
  await site.getByRole('button', { name: '保存唱片设置', exact: true }).click(); check('vinyl-customization');
  await chooseRoomScene(site, 'warm');
  await chooseRoomScene(site, 'pixel');
  await site.locator('.room-record').first().dblclick();
  await site.waitForFunction(() => document.querySelector('.room-turntable')?.dataset.spinning === 'true'); check('cabin-looks-and-turntable');
  await site.getByRole('button', { name: /唱片卡片/ }).click(); const card = site.getByRole('dialog', { name: '唱片卡片：本地验证专辑' });
  await card.getByPlaceholder(/第一次听的场景/).fill('安装后的第一张'); await card.locator('.record-card-saved', { hasText: '已保存' }).waitFor();
  await card.getByRole('button', { name: '关闭唱片卡片' }).click(); check('record-card-notes');
  await site.getByRole('button', { name: '软件设置', exact: true }).first().click();
  const shell = application.windows().find((page) => page.url().startsWith('album-desktop://shell'));
  await shell.locator('#zoom').fill('110'); await shell.locator('#zoom').dispatchEvent('change'); await shell.getByRole('button', { name: '完成', exact: true }).click();
  check('settings-open-and-save');
  if (process.env.ALBUM_QA_SKIP_WALLPAPER !== '1') {
  await site.getByRole('button', { name: '设为桌面动态背景', exact: true }).click();
  await site.getByRole('button', { name: '停止桌面动态背景', exact: true }).waitFor({ timeout: 20000 });
  await site.getByRole('button', { name: '停止桌面动态背景', exact: true }).click(); check('native-desktop-wallpaper');
  } else check('desktop-wallpaper-not-tested-on-hosted-runner');
  await site.screenshot({ path: path.join(output, 'cabin.png') });
  await application.close(); application = null;
  await launch(); await site.locator('.cabin-pixel').waitFor(); await site.locator('.room-record').first().waitFor();
  const saved = JSON.parse(fs.readFileSync(path.join(profile, 'collection.json'), 'utf8'));
  assert.equal(saved.items[0].title, '本地验证专辑'); assert.equal(saved.items[0].notes, '安装后的第一张'); check('collection-notes-and-style-survive-restart');
  assert.equal(report.pageErrors.length, 0, JSON.stringify(report.pageErrors)); report.passed = true;
})().catch((error) => { report.error = error.stack; report.passed = false; process.exitCode = 1; }).finally(async () => {
  if (!report.passed && site && !site.isClosed()) await site.screenshot({ path: path.join(output, 'failure.png') }).catch(() => {});
  if (application) await application.close().catch(() => {});
  fs.rmSync(profile, { recursive: true, force: true });
  fs.writeFileSync(path.join(output, 'report.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
});
