'use strict';
const { _electron } = require('playwright'), fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const { mountFixture, albums } = require('./ui-fixture.cjs');
const desktop = path.resolve(__dirname, '..'), output = path.join(desktop, 'test-results');
const env = { ...process.env, ALBUM_DESKTOP_TEST_PROFILE: path.join(output, `library-ui-profile-${Date.now()}`) }; delete env.ELECTRON_RUN_AS_NODE;
const executablePath = process.env.ALBUM_QA_EXE || path.join(desktop, 'node_modules/electron/dist/electron.exe');
const report = { executablePath, startedAt: new Date().toISOString(), fixtureData: true, paidAIRequests: 0, productionWrites: 0, checks: [], pageErrors: [] };
const check = (name, detail = {}) => { report.checks.push({ name, passed: true, ...detail }); console.log('PASS ' + name); };
let app, site, host;
const items = Array.from({ length: 14 }, (_, i) => ({ ...albums[i % albums.length], id: `library-fixture-${i}`, externalIds: i < albums.length ? albums[i].externalIds : undefined, collectionId: undefined, title: i < albums.length ? albums[i].title : `${albums[i % albums.length].title} · 测试 ${i}`, tags: i === 0 ? ['album', 'qq', 'Rock'] : [], addedAt: `2026-09-${String(29 - i).padStart(2, '0')}` }));
const saved = () => site.evaluate(() => JSON.parse(localStorage.getItem('album-circle-library-v1-desktop-qa-only')));
const setStyle = async (showroom) => { await host.evaluate((showroom) => window.albumDesktop.settings('apply', { showroom }), showroom); await site.waitForFunction((value) => document.documentElement.dataset.desktopShowroom === value, showroom); };
(async () => {
  app = await _electron.launch({ executablePath, args: process.env.ALBUM_QA_EXE ? [] : [desktop], env }); app.context().setDefaultTimeout(18000); await app.firstWindow();
  for (let i = 0; i < 100; i++) { site = app.context().pages().find((p) => p.url().startsWith('https://album-circle.vercel.app')); host = app.context().pages().find((p) => p.url() === 'album-desktop://shell/index.html'); if (site && host) break; await new Promise((r) => setTimeout(r, 100)); }
  site.on('pageerror', (error) => report.pageErrors.push(error.message));
  await mountFixture(app, site, { items });
  await site.getByRole('button', { name: '管理唱片盒', exact: true }).click();
  const manager = site.getByRole('dialog', { name: '管理唱片盒' });
  await manager.getByLabel('新唱片盒名称').fill('周末收藏'); await manager.getByRole('button', { name: '新建唱片盒', exact: true }).click();
  await manager.getByRole('checkbox', { name: `唱片盒包含 ${items[0].title}`, exact: true }).check();
  await manager.getByRole('checkbox', { name: `唱片盒包含 ${items[1].title}`, exact: true }).check();
  await manager.getByLabel('重命名唱片盒').fill('周末唱片'); await manager.getByRole('button', { name: '重命名', exact: true }).click();
  await manager.getByLabel('新唱片盒名称').fill('最爱'); await manager.getByRole('button', { name: '新建唱片盒', exact: true }).click();
  await manager.getByRole('checkbox', { name: `唱片盒包含 ${items[0].title}`, exact: true }).check();
  await manager.screenshot({ path: path.join(output, 'record-boxes.png') });
  await manager.getByRole('button', { name: '完成整理', exact: true }).click();
  const boxes = (await saved()).rooms['desktop-qa-room'].boxes;
  assert.equal(boxes.length, 2); assert.equal(boxes[0].name, '周末唱片');
  await site.getByLabel('筛选唱片盒').selectOption(boxes[0].id); assert.equal(await site.locator('.cabinet-tile').count(), 2);
  await site.getByLabel('筛选流派').selectOption('Rock'); assert.equal(await site.locator('.cabinet-tile').count(), 1);
  await site.getByLabel('筛选年代').selectOption('2000'); await site.getByLabel('筛选来源').selectOption('qq'); assert.equal(await site.locator('.cabinet-tile').count(), 1);
  check('create-rename-multiple-boxes-and-combined-filters');
  await site.getByRole('button', { name: '自定义唱片', exact: true }).click();
  const editor = site.getByRole('dialog', { name: '自定义唱片' });
  await editor.getByLabel('黑胶底色', { exact: true }).fill('#a23856'); await editor.getByLabel('黑胶透明度').fill('62');
  await editor.getByRole('button', { name: '复古金彩', exact: true }).click();
  await editor.getByLabel('黑胶底色', { exact: true }).fill('#111215'); await editor.getByLabel('黑胶透明度').fill('100');
  await editor.getByRole('button', { name: '查看完整黑胶', exact: true }).click();
  await editor.screenshot({ path: path.join(output, 'classic-splatter.png') });
  await editor.getByRole('button', { name: '查看封面与黑胶', exact: true }).click();
  await editor.getByLabel('黑胶底色', { exact: true }).fill('#a23856'); await editor.getByLabel('黑胶透明度').fill('62');
  await editor.getByLabel('泼溅颜色数量', { exact: true }).selectOption('1'); assert.equal(await editor.locator('input[type=color]').count(), 2);
  await editor.getByLabel('泼溅颜色 1', { exact: true }).fill('#f4db92');
  await editor.getByLabel('泼溅颜色数量', { exact: true }).selectOption('2'); assert.equal(await editor.locator('input[type=color]').count(), 3);
  await editor.getByLabel('泼溅颜色 2', { exact: true }).fill('#a53d45');
  await editor.getByLabel('泼溅颜色数量', { exact: true }).selectOption('3'); assert.equal(await editor.locator('input[type=color]').count(), 4);
  await editor.getByLabel('泼溅颜色 3', { exact: true }).fill('#eadbc0');
  await editor.getByRole('button', { name: '查看完整黑胶', exact: true }).click();
  await editor.screenshot({ path: path.join(output, 'splatter-three-colours.png') });
  await editor.getByRole('button', { name: '查看封面与黑胶', exact: true }).click();
  await editor.getByLabel('流派标签', { exact: true }).fill('爵士，电子');
  await editor.screenshot({ path: path.join(output, 'custom-vinyl.png') });
  await editor.getByRole('button', { name: '保存唱片设置', exact: true }).click();
  await site.getByLabel('筛选流派').selectOption('爵士');
  assert.equal(await site.locator('.cabinet-tile').count(), 1);
  const vinyl = site.locator('.cabinet-vinyl').first();
  assert.equal(await vinyl.getAttribute('data-splatter'), 'true');
  assert.equal(await vinyl.evaluate((node) => getComputedStyle(node).opacity), '0.62');
  assert.equal(await vinyl.evaluate((node) => getComputedStyle(node).getPropertyValue('--vinyl-base').trim()), '#a23856');
  assert.equal(await vinyl.locator('[data-template="radial-v2"]').getAttribute('data-colour-count'), '3');
  assert.deepEqual(await vinyl.locator('[data-splash-colour]').evaluateAll((nodes) => nodes.map((node) => node.dataset.splashColour)), ['#f4db92', '#a53d45', '#eadbc0']);
  check('per-album-base-opacity-one-to-three-colours-fixed-mixture-presets-and-manual-genres');
  await site.locator('.cabinet-tile').first().click(); await site.locator('.detail-story h2').waitFor();
  assert.equal(await site.locator('.vinyl-shadow').getAttribute('data-splatter'), 'true');
  check('custom-vinyl-applies-to-detail');
  await site.getByRole('button', { name: '展柜', exact: true }).click(); await site.getByRole('button', { name: '清除音乐筛选' }).click();
  await setStyle('room'); await site.locator('.room-record').first().waitFor();
  assert.equal(await site.locator('.room-record').count(), 12);
  await site.waitForFunction(() => document.querySelector('.cabin-scene-art').complete && [...document.querySelectorAll('.room-record img')].every((img) => img.complete && img.naturalWidth > 0));
  await site.locator('.room-scene').screenshot({ path: path.join(output, 'warm-cabin.png') });
  await site.getByRole('button', { name: '下一排唱片' }).click(); assert.equal(await site.locator('.room-record').count(), 10); assert.equal(await site.locator('.room-record-empty').count(), 2);
  await site.locator('.room-scene').screenshot({ path: path.join(output, 'warm-cabin-empty-slots.png') });
  await site.getByRole('button', { name: '上一排唱片' }).click();
  check('reference-one-room-twelve-live-covers-pagination-and-masked-empty-slots');
  await site.getByRole('button', { name: '切换像素风格', exact: true }).click();
  await site.waitForFunction(() => document.querySelectorAll('.pixel-artwork canvas.is-painted').length === 12);
  await site.locator('.room-scene').screenshot({ path: path.join(output, 'pixel-cabin.png') });
  assert.equal(await site.locator('.cabin-scene-art').getAttribute('src'), '/room-scenes/pixel-cabin.png');
  await site.reload(); await site.locator('.cabin-pixel').waitFor();
  assert.equal((await saved()).rooms['desktop-qa-room'].look, 'pixel');
  check('reference-two-pixel-covers-and-persistent-style-switch');
  await setStyle('coverflow'); await site.getByRole('region', { name: 'Coverflow 专辑浏览' }).waitFor();
  await site.getByLabel('筛选唱片盒').selectOption(boxes[1].id); assert.equal(await site.locator('.flow-card').count(), 1);
  await site.getByRole('button', { name: '自定义唱片', exact: true }).click(); await editor.waitFor();
  assert.equal(await editor.getByLabel('黑胶底色', { exact: true }).inputValue(), '#a23856');
  assert.equal(await editor.getByLabel('泼溅颜色 3', { exact: true }).inputValue(), '#eadbc0');
  await editor.getByLabel('泼溅颜色 1', { exact: true }).fill('#0000ff');
  await site.keyboard.press('Escape'); await editor.waitFor({ state: 'hidden' });
  assert.deepEqual(Object.values((await saved()).styles)[0].splashes, ['#f4db92', '#a53d45', '#eadbc0']);
  check('coverflow-box-filters-and-shared-record-style');
  await setStyle('original'); await site.getByRole('button', { name: '管理唱片盒', exact: true }).click();
  await manager.getByRole('button', { name: '最爱', exact: false }).click();
  await manager.getByRole('button', { name: '删除这个唱片盒' }).click(); await manager.getByRole('button', { name: '确认删除唱片盒' }).click();
  await manager.getByRole('button', { name: '完成整理' }).click();
  assert.equal(await site.locator('.cabinet-tile').count(), 14);
  assert.equal((await saved()).rooms['desktop-qa-room'].boxes.length, 1);
  check('delete-box-preserves-library-and-resets-stale-filter');
  const cdp = await site.context().newCDPSession(site);
  for (const width of [960, 1920, 3840]) {
    await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1440, deviceScaleFactor: 1, mobile: false }); await setStyle('room');
    const rect = await site.locator('.room-scene').evaluate((node) => { const rect = node.getBoundingClientRect(); return { left: rect.left, right: rect.right, scrollWidth: document.documentElement.scrollWidth }; });
    assert.ok(rect.left >= 0 && rect.right <= width && rect.scrollWidth <= width + 1); check(`cabin-responsive-${width}`, rect);
  }
  await cdp.send('Emulation.clearDeviceMetricsOverride'); await cdp.detach();
  // A genuine application restart retains the same isolated user directory.
  assert.equal(await app.evaluate(() => globalThis.__qaBlockedWrites), 0);
  await app.close(); app = await _electron.launch({ executablePath, args: process.env.ALBUM_QA_EXE ? [] : [desktop], env }); await app.firstWindow();
  for (let i = 0; i < 100; i++) { site = app.context().pages().find((p) => p.url().startsWith('https://album-circle.vercel.app')); if (site) break; await new Promise((r) => setTimeout(r, 100)); }
  await mountFixture(app, site, { items }); await site.locator('.cabin-pixel').waitFor();
  assert.equal((await saved()).rooms['desktop-qa-room'].boxes[0].name, '周末唱片'); assert.equal((await saved()).styles['qq:' + items[0].externalIds.qqAlbumMid].opacity, 62);
  check('full-exe-restart-retains-boxes-genres-vinyl-and-cabin-look');
  host = app.context().pages().find((page) => page.url() === 'album-desktop://shell/index.html');
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1 }); });
  await host.evaluate(() => window.albumDesktop.command('clear'));
  await mountFixture(app, site, { items }); await site.locator('.cabin-pixel').waitFor();
  assert.equal((await saved()).rooms['desktop-qa-room'].boxes[0].name, '周末唱片');
  assert.equal((await saved()).styles['qq:' + items[0].externalIds.qqAlbumMid].opacity, 62);
  assert.deepEqual((await saved()).genres['qq:' + items[0].externalIds.qqAlbumMid], ['爵士', '电子']);
  check('login-and-cache-reset-preserves-local-record-library');
  assert.equal(report.pageErrors.length, 0); assert.equal(await app.evaluate(() => globalThis.__qaBlockedWrites), 0);
  report.passed = true;
})().catch((error) => { report.error = error.stack; report.passed = false; process.exitCode = 1; }).finally(async () => {
  if (!report.passed && site && !site.isClosed()) await site.screenshot({ path: path.join(output, 'library-failure.png'), fullPage: true }).catch(() => {});
  if (app) await app.close().catch(() => {});
  report.finishedAt = new Date().toISOString(); fs.writeFileSync(path.join(output, 'library-ui-report.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
});
