'use strict';
// Tray / menu-bar icon that follows the selected pet (generated by npm run icons).
const path = require('node:path');
const PET_IDS = ['cat', 'chick', 'bunny', 'bear', 'fox'];
const normalize = (id) => PET_IDS.includes(id) ? id : 'cat';
// macOS loads `<id>Template.png` and picks up `@2x` automatically; the
// "Template" suffix lets the menu bar tint it for light / dark.
function trayIconPath(petId, platform = process.platform, base = path.join(__dirname, 'assets', 'tray')) {
  const id = normalize(petId);
  if (platform === 'darwin') return path.join(base, `${id}Template.png`);
  if (platform === 'win32') return path.join(base, `${id}.ico`);
  return path.join(base, `${id}.png`);
}
function createTrayPet({ getTray, nativeImage, platform = process.platform }) {
  let current = 'cat';
  return {
    get petId() { return current; },
    // Internal: called whenever the companion snapshot reports a pet.
    setTrayPet(petId) {
      const id = normalize(petId); if (id === current && getTray()?.__petId === id) return false;
      current = id; const tray = getTray(); if (!tray) return true;
      const image = nativeImage.createFromPath(trayIconPath(id, platform));
      if (platform === 'darwin') image.setTemplateImage?.(true);
      if (!image.isEmpty()) { tray.setImage(image); tray.__petId = id; }
      return true;
    }
  };
}
module.exports = { trayIconPath, createTrayPet, PET_IDS };
